anihalaney/rwa-trivia

README.md

improve markdown by escaping the slash

improve markdown by escaping the slash

---

src/app/components/question/questions.component.ts

Removed unnecessary/duplicated code.

Remove category service code

---

functions/app.ts

change adminOnly middelware, format code and removed tslint errors

changed adminOnly middelware to firestore

---

firestorage-rules.txt
package.json
src/app/bulk/components/bulk-upload/bulk-upload.component.html
src/app/bulk/components/bulk-upload/bulk-upload.component.ts
src/app/components/app/app.component.ts
src/app/core/core.module.ts
src/app/core/services/authentication.service.ts
src/app/core/services/bulk.service.ts
src/app/core/services/index.ts
src/app/core/services/user.service.ts
src/app/core/store/actions/user.actions.ts
src/app/core/store/app-store.ts
src/app/core/store/effects/question.effects.ts
src/app/core/store/effects/user.effects.ts
src/app/core/store/reducers/user.reducer.ts
src/app/model/bulk-upload-file-info.ts
src/app/model/question.ts
src/app/model/user.ts
src/app/shared/components/bulk-summary-question/bulk-summary-question.component.html
src/app/shared/components/bulk-summary-question/bulk-summary-question.component.ts
src/app/shared/components/bulk-summary-table/bulk-summary-table.component.html
src/app/shared/components/bulk-summary-table/bulk-summary-table.component.ts
src/app/shared/shared.module.ts
src/app/user/components/profile-settings/profile-settings.component.html
src/app/user/components/profile-settings/profile-settings.component.scss
src/app/user/components/profile-settings/profile-settings.component.ts
src/app/user/user.module.ts

Improper tagging on bulk upload
Ability to download file upload by user and Admin
Profile-setting is work in progress in this pull request

Profile settings

---

firestore-rules.txt
src/app/core/services/bulk.service.ts
src/app/core/services/user.service.ts
src/app/core/store/actions/user.actions.ts
src/app/core/store/effects/user.effects.ts
src/app/core/store/reducers/user.reducer.ts
src/app/user/components/profile-settings/profile-settings.component.ts

Solved issue with saving profile for non admin user

---

package.json

set elasticsearch index for production

set firebase default project

---

src/app/bulk/components/bulk-upload/bulk-upload.component.ts
src/app/core/services/question.service.ts
src/app/shared/components/questions-table/questions-table.component.html

Issues related to bulk upload validations

Dark theme bug

---

src/app/core/services/game.service.ts
src/app/user/components/game-card/game-card.component.html
src/app/user/components/game-card/game-card.component.scss
src/app/user/components/game-card/game-card.component.ts

Currently active game

---

src/app/components/app/app.component.ts
src/app/components/footer/footer.component.html
src/app/components/footer/footer.component.scss
src/app/components/footer/footer.component.ts
src/app/components/side-nav/side-nav.component.html
src/app/components/side-nav/side-nav.component.scss
src/app/components/side-nav/side-nav.component.ts
src/app/core/services/question.service.ts
src/app/game-play/components/game-dialog/game-dialog.component.ts
src/app/user/components/my-questions/my-questions.component.html
src/app/user/components/my-questions/my-questions.component.scss
src/app/user/components/user-stats-card/user-stats-card.component.html
src/app/user/components/user-stats-card/user-stats-card.component.scss
src/app/user/routing/user.route.ts
src/app/user/store/effects/user.effects.ts

Dashboard bugs

---

src/app/components/side-nav/side-nav.component.html
src/app/user/components/user-stats-card/user-stats-card.component.html
src/app/user/components/user-stats-card/user-stats-card.component.scss

BW-147,148
@anihalaney , you can do code review

Side nav stat view changes

---

src/app/stats/components/leaderboard/leaderboard.component.html

Main page category leaderboard changes

---

src/app/components/header/header.component.html
src/app/user/components/invite-friends/invite-friends-dialog/invite-friends-dialog.component.html
src/app/user/components/invite-friends/invite-friends-dialog/invite-mail-friends/invite-mail-friends.component.html
src/app/user/components/invite-friends/invite-friends-dialog/invite-mail-friends/invite-mail-friends.component.scss
src/app/user/components/invite-friends/invite-friends-dialog/invite-mail-friends/invite-mail-friends.component.ts
src/app/user/components/invite-friends/invite-friends.component.html
src/app/user/components/invite-friends/invite-friends.component.scss
src/app/user/components/profile-settings/profile-settings.component.html
src/app/user/components/profile-settings/profile-settings.component.scss

Friend page

---

src/app/components/dashboard/dashboard.component.html
src/app/game-play/components/game-dialog/game-dialog.component.html
src/app/game-play/components/game-dialog/game-dialog.component.ts
src/app/game-play/components/game-over/game-over.component.html
src/app/game-play/components/game-over/game-over.component.scss
src/app/game-play/components/game-over/game-over.component.ts
src/app/game-play/components/game-question/game-question.component.html
src/app/game-play/components/game-question/game-question.component.scss
src/app/game-play/components/game-question/game-question.component.ts
src/app/game-play/components/report-game/report-game.component.html
src/app/game-play/components/report-game/report-game.component.scss
src/app/game-play/components/report-game/report-game.component.ts
src/app/model/question.ts
src/app/shared/components/author/author.component.html
src/app/shared/components/author/author.component.scss
src/app/shared/components/author/author.component.ts
src/app/shared/components/index.ts
src/app/shared/components/question/question.component.html
src/app/shared/components/question/question.component.scss
src/app/shared/components/question/question.component.ts
src/app/shared/shared.module.ts
src/app/user/components/invite-friends/invite-friends.component.ts

Author info

---

src/app/core/services/user.service.ts
src/app/model/user.ts

Sign up profile

---

src/app/core/services/user.service.ts
src/app/game-play/components/game-dialog/game-dialog.component.html
src/app/game-play/components/game-dialog/game-dialog.component.scss
src/app/game-play/components/game-over/game-over.component.html
src/app/game-play/components/game-over/game-over.component.scss
src/app/model/user.ts
src/app/shared/components/social-palette/social-palette.component.scss
src/app/stats/components/realtime-stats/realtime-stats.component.html
src/app/user/components/my-questions/my-questions.component.html
src/app/user/routing/user.route.ts
src/app/user/store/effects/user.effects.ts
src/styles/global.scss

The resolved issue list is as follows : 
(1) Admin and Bulk related link issue in footer.
(2) Not able to load published and unpublished question on my-question link on refresh.
(3) Social icon css issue for blog and game over dialog.
(4) Game over Text didn't come while sharing score image on social media at Game Over dialog.
(5) While playing game loading,1st badge and 2 badge screen is not responsive to mobile resolution.
(6) Changed route for create question from my-question tab.

Question my question

---

functions/db/firebase-functions.ts
src/app/components/app/app.component.ts
src/app/model/constants.ts

Invite friends changes

---

functions/controllers/question.controller.ts
functions/routes/question-routes.ts
functions/utils/ESUtils.ts
src/app/core/services/question.service.ts
src/app/core/store/effects/question.effects.ts

Done changes related to restrict question of day for 24 hours

---

functions/utils/system-stats-calculations.ts
src/app/stats/components/leaderboard/leaderboard.component.html

changed promise structure
for category leader board corrected leader number

Main page real time stat

---

functions/controllers/game.controller.ts
src/app/game-play/components/game-dialog/game-dialog.component.ts

Done changes related to resolve game related issues

---

src/app/game-play/components/game-over/game-over.component.html
src/app/game-play/components/game-over/game-over.component.scss
src/app/shared/components/author/author.component.html
src/app/shared/components/author/author.component.scss
src/app/shared/components/question/question.component.scss

Display user profile after  name for author.

---

functions/controllers/game.controller.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/game-play/components/game-dialog/game-dialog.component.ts
src/app/model/game.ts

Rematch friend invitation

---

functions/controllers/general.controller.ts
functions/controllers/question.controller.ts
functions/utils/ESUtils.ts
src/app/game-play/components/game-dialog/game-dialog.component.html
src/app/game-play/components/game-dialog/game-dialog.component.ts
src/app/game-play/components/game-question/game-question.component.html
src/app/game-play/components/game-question/game-question.component.ts
src/app/model/game.ts

Done changes related to change subtitle in blog

---

src/app/game-play/components/game-dialog/game-dialog.component.html
src/app/game-play/components/game-question/game-question.component.html
src/app/game-play/components/game-question/game-question.component.scss
src/app/game-play/components/game-question/game-question.component.ts
src/styles/theme/_text.scss

Added redirection message

---

functions/controllers/question.controller.ts
package.json
src/app/components/dashboard/dashboard.component.html
src/app/core/services/game.service.ts
src/app/core/services/social.service.ts
src/app/game-play/components/game-dialog/game-dialog.component.html
src/app/game-play/components/game-dialog/game-dialog.component.scss
src/app/game-play/components/game-dialog/game-dialog.component.ts
src/app/game-play/components/game-over/game-over.component.html
src/app/game-play/components/game-over/game-over.component.scss
src/app/game-play/components/game-question/game-question.component.html
src/app/game-play/components/game-question/game-question.component.scss
src/app/game-play/components/game-question/game-question.component.ts
src/app/model/game.ts
src/app/model/question.ts
src/app/social/components/blog/blog.component.ts
src/styles/global.scss
src/styles/theme/_text.scss

Reverts anihalaney/rwa-trivia#184

Revert "Bw 211"

---

e2e/app.e2e-spec.ts
e2e/social/newsletter/newsletter.e2e-spec.ts
e2e/social/newsletter/newsletter.po.ts
src/app/social/components/newsletter/newsletter.component.html

it shows many changes as part-22 does not have changes from part-21

Bw 214 - e2e test for news componenet

---

projects/trivia/src/app/dashboard/component/game-card/game-card.component.html
projects/trivia/src/app/dashboard/component/game-card/game-card.component.scss
projects/trivia/src/app/dashboard/component/game-card/game-card.component.tns.html
projects/trivia/src/app/dashboard/component/game-card/game-card.component.ts

BW-738 #comment changes for game over button hide

---

functions/db/firebase.functions.ts

BW-737 #comment changes for push-notification message

---

functions/db/firebase.functions.ts
functions/package.json
functions/utils/achievement-mechanics.ts
functions/utils/game-mechanics.ts
functions/utils/push-notifications.ts
projects/shared-library/src/lib/shared/model/application-settings.ts

BW-717 #comment changes for notification template

---

projects/shared-library/src/lib/core/services/utils.tns.ts
projects/shared-library/src/lib/shared/components/recent-games/recent-game-card/recent-game-card.component.html
projects/shared-library/src/lib/shared/components/recent-games/recent-game-card/recent-game-card.component.tns.html
projects/shared-library/src/lib/shared/model/game.ts
projects/trivia/src/app/game-play/components/game-dialog/game-dialog.ts
projects/trivia/src/app/game-play/components/game-over/game-over.ts

BW-750 #comment changes for game over fix bug for tie and draw condition

---

projects/trivia/src/app/dashboard/component/question/question.component.ts
projects/trivia/src/app/game-play/components/game-over/game-over.ts
projects/trivia/src/app/user/components/game-profile/game-profile.component.tns.html
projects/trivia/src/app/user/routing/user.route.ts
projects/trivia/src/styles/global.scss

1) User Online status (green dot on profile ) is not displayed properly
2) the User without doing login if user go to My Profile Page It Should Redirect to dashboard.(Web)
3) Verify that in the "Question of the Day!" section, an option can be selected as answer. (Web)
4) verify that on click of x the invite friend popup is not closing (Web) : it happens randomly
5) Login scrolling not working in mobile device(WEB)

BW-747 #comment  Fixed below bugs

---

App_Resources/Android/src/main/AndroidManifest.xml
projects/shared-library/src/lib/core/auth/mobile/firebase-auth.service.ts
projects/shared-library/src/lib/shared/components/question-form/question-form.component.ts
projects/trivia-editor/src/app/add-question/add-question.component.html
projects/trivia-editor/src/app/add-question/add-question.component.ts
projects/trivia/src/app/user/components/question-add-update/question-add-update.component.tns.html
projects/trivia/src/app/user/components/question-add-update/question-add-update.ts

1) Some time error message is not displaying in add question in mobile,
2) In web and mobile auto tag is not working while question is rich editor
3)) Some time user logout after change password in mobile

BW-746  Fixed Bugs:

---

projects/shared-library/src/lib/core/store/actions/user.actions.ts
projects/shared-library/src/lib/core/store/effects/user.effects.ts
projects/shared-library/src/lib/core/store/reducers/index.ts
projects/shared-library/src/lib/core/store/reducers/user.reducer.ts
projects/shared-library/src/lib/shared/components/questions-search/questions-search.component.spec.ts
projects/shared-library/src/lib/shared/components/questions-search/questions-search.component.ts
projects/shared-library/src/lib/shared/components/questions-table/questions-table.component.spec.ts
projects/shared-library/src/lib/shared/components/questions-table/questions-table.component.ts
projects/shared-library/src/lib/shared/components/rejected-question-content/rejected-question-content.component.spec.ts
projects/shared-library/src/lib/shared/components/render-question/render-question.component.html
projects/shared-library/src/lib/shared/components/render-question/render-question.component.spec.ts
projects/shared-library/src/lib/shared/components/render-question/render-question.component.ts
projects/shared-library/src/lib/shared/components/signup-extra-info/signup-extra-info.component.spec.ts
projects/shared-library/src/lib/shared/components/signup-extra-info/signup-extra-info.component.ts
projects/shared-library/src/lib/shared/components/social-palette/social-palette.component.spec.ts
projects/shared-library/src/lib/shared/components/user-card/user-card.component.spec.ts
projects/shared-library/src/lib/shared/components/user-card/user-card.component.ts
projects/shared-library/src/lib/shared/model/friends.ts
projects/trivia/src/app/user/components/game-profile/game-profile.component.spec.ts
projects/trivia/src/app/user/components/invite-friends/invite-friends.component.spec.ts
projects/trivia/src/app/user/components/invite-friends/invite-friends.component.tns.ts
projects/trivia/src/app/user/components/invite-friends/invite-friends.component.ts
projects/trivia/src/app/user/components/invite-friends/invite-friends.ts
test/data/application-settings.ts
test/data/bulk-uploads.ts
test/data/friends-list.ts
test/data/index.ts
test/data/questions.ts
test/data/user-list.ts

BW-771: Rejected Question Content Component

---

projects/trivia/src/app/components/app/app.component.spec.ts
projects/trivia/src/app/components/app/app.component.ts

Bw 795 Unit test for App component 

---

projects/trivia/src/app/game-play/components/report-game/report-game.component.spec.ts
test/data/question.ts

BW-802 unit test for ReportGameComponent.

---

projects/trivia/src/app/user/components/profile-settings/location-reset-dialog/location-reset-dialog.component.spec.ts
projects/trivia/src/app/user/components/profile-settings/location-reset-dialog/location-reset-dialog.component.ts

BW-803 Unit test for location-reset-dialog component

---

projects/trivia/src/app/components/invitation-redirection/invitation-redirection.component.spec.ts
projects/trivia/src/app/components/invitation-redirection/invitation-redirection.component.ts

BW-807 #Unit test invitation redirection component

---

projects/trivia/src/app/game-play/store/actions/game-play.actions.spec.ts

BW-808 Unit test game-play actions.

---

projects/trivia/src/app/user/store/actions/user.action.spec.ts

BW-809 unit test for user action

---

projects/trivia/src/app/user/store/reducers/user.reducer.spec.ts

BW-810 unit test user reducer

---

projects/trivia/src/app/components/achievements/achievements.component.spec.ts
projects/trivia/src/app/components/achievements/achievements.component.ts
projects/trivia/src/app/components/header/header.component.spec.ts
projects/trivia/src/app/components/header/header.component.ts
projects/trivia/src/app/components/profile-card/profile-card.component.spec.ts
projects/trivia/src/app/components/profile-card/profile-card.component.ts

BW-811 Unit test written for Achievements, Header and Profile-card 

---

projects/trivia/src/app/components/app/app.component.ts

BW-822  Resolve issue for web when user connection is lost. it was creating unnecessary function call

---

projects/shared-library/src/lib/core/store/reducers/categories.reducer.spec.ts

BW-814 Unit test for categories.reducer

---

projects/shared-library/src/lib/core/store/reducers/application-settings.reducer.spec.ts
projects/shared-library/src/lib/core/store/reducers/game.reducer.spec.ts

BW-813 Unit test for game and application settings reducer

---

projects/shared-library/src/lib/core/store/reducers/user.reducer.spec.ts

Bw 815 Unit test User reducer shared library

---

projects/trivia/src/tests/new-game.component.ts

One PR is already merged. In this PR removed unnecessary code

BW-837 Unit test Mobile: new game component 
